### ISSUE TITLE
The error after running actor python file

### ISSUE THREAD

**Issue by StevenUST** [submit-paper/Danzero_plus#4]
After I install all the required libraries, I try to run the program with command "python actor_n/actor.py".
However, it gives this output which is not desired:

WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
Process Process-1:
Traceback (most recent call last):
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "actor_n/actor.py", line 191, in exit_wrapper
    run_one_player(index, *x, **kw)
  File "actor_n/actor.py", line 157, in run_one_player
    player = Player(args)
  File "actor_n/actor.py", line 67, in __init__
    create_experiment_dir(self.args, f'Client{args.client_index}-')
  File "/home/steventse7340/Research2024-Winter/Danzero_plus-main/actor_n/utils/data_trans.py", line 46, in create_experiment_dir
    args.exp_path.mkdir()
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/root/log/Client0'
Process Process-2:
Traceback (most recent call last):
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "actor_n/actor.py", line 191, in exit_wrapper
    run_one_player(index, *x, **kw)
  File "actor_n/actor.py", line 157, in run_one_player
    player = Player(args)
  File "actor_n/actor.py", line 67, in __init__
    create_experiment_dir(self.args, f'Client{args.client_index}-')
  File "/home/steventse7340/Research2024-Winter/Danzero_plus-main/actor_n/utils/data_trans.py", line 46, in create_experiment_dir
    args.exp_path.mkdir()
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/root/log/Client1'
Process Process-3:
Traceback (most recent call last):
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "actor_n/actor.py", line 191, in exit_wrapper
    run_one_player(index, *x, **kw)
  File "actor_n/actor.py", line 157, in run_one_player
    player = Player(args)
  File "actor_n/actor.py", line 67, in __init__
    create_experiment_dir(self.args, f'Client{args.client_index}-')
  File "/home/steventse7340/Research2024-Winter/Danzero_plus-main/actor_n/utils/data_trans.py", line 46, in create_experiment_dir
    args.exp_path.mkdir()
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/root/log/Client2'
Process Process-4:
Traceback (most recent call last):
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "actor_n/actor.py", line 191, in exit_wrapper
    run_one_player(index, *x, **kw)
  File "actor_n/actor.py", line 157, in run_one_player
    player = Player(args)
  File "actor_n/actor.py", line 67, in __init__
    create_experiment_dir(self.args, f'Client{args.client_index}-')
  File "/home/steventse7340/Research2024-Winter/Danzero_plus-main/actor_n/utils/data_trans.py", line 46, in create_experiment_dir
    args.exp_path.mkdir()
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/home/steventse7340/anaconda3/envs/guandan3_6/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/root/log/Client3'

What causes these errors?

**Comment by StevenUST** [comment]
> It's obvious that the errors are caused by "No such file or directory: '/home/root/log/Clientx' ". You can check whether this directory path exists or you can change some settings in the parser.add_argument.
> 
> After this, do you run the code in dockers? It's recommend to run the project using dockers, otherwise there may be other errors.

Thanks. I try to run it in dockers
